package todojava.exercise.TestData;

public class APPBannerDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.BANNER_ID
     *
     * @mbggenerated
     */
    private String bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.APP_PLATFORM
     *
     * @mbggenerated
     */
    private String appPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.APP_CHANNEL
     *
     * @mbggenerated
     */
    private String appChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.APP_NAME
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.BANNER_IMG_URL
     *
     * @mbggenerated
     */
    private String bannerImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.BANNER_IMG_HREF
     *
     * @mbggenerated
     */
    private String bannerImgHref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.BANNER_PRIORITY
     *
     * @mbggenerated
     */
    private String bannerPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.BANNER_DESC
     *
     * @mbggenerated
     */
    private String bannerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.CREATE_DATE
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.UPDATE_DATE
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.LAST_UPDATE_USER
     *
     * @mbggenerated
     */
    private String lastUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BANNER.APP_TERM_TYPE
     *
     * @mbggenerated
     */
    private String appTermType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.BANNER_ID
     *
     * @return the value of APP_BANNER.BANNER_ID
     *
     * @mbggenerated
     */
    public String getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.BANNER_ID
     *
     * @param bannerId the value for APP_BANNER.BANNER_ID
     *
     * @mbggenerated
     */
    public void setBannerId(String bannerId) {
        this.bannerId = bannerId == null ? null : bannerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.APP_PLATFORM
     *
     * @return the value of APP_BANNER.APP_PLATFORM
     *
     * @mbggenerated
     */
    public String getAppPlatform() {
        return appPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.APP_PLATFORM
     *
     * @param appPlatform the value for APP_BANNER.APP_PLATFORM
     *
     * @mbggenerated
     */
    public void setAppPlatform(String appPlatform) {
        this.appPlatform = appPlatform == null ? null : appPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.APP_CHANNEL
     *
     * @return the value of APP_BANNER.APP_CHANNEL
     *
     * @mbggenerated
     */
    public String getAppChannel() {
        return appChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.APP_CHANNEL
     *
     * @param appChannel the value for APP_BANNER.APP_CHANNEL
     *
     * @mbggenerated
     */
    public void setAppChannel(String appChannel) {
        this.appChannel = appChannel == null ? null : appChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.APP_NAME
     *
     * @return the value of APP_BANNER.APP_NAME
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.APP_NAME
     *
     * @param appName the value for APP_BANNER.APP_NAME
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.BANNER_IMG_URL
     *
     * @return the value of APP_BANNER.BANNER_IMG_URL
     *
     * @mbggenerated
     */
    public String getBannerImgUrl() {
        return bannerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.BANNER_IMG_URL
     *
     * @param bannerImgUrl the value for APP_BANNER.BANNER_IMG_URL
     *
     * @mbggenerated
     */
    public void setBannerImgUrl(String bannerImgUrl) {
        this.bannerImgUrl = bannerImgUrl == null ? null : bannerImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.BANNER_IMG_HREF
     *
     * @return the value of APP_BANNER.BANNER_IMG_HREF
     *
     * @mbggenerated
     */
    public String getBannerImgHref() {
        return bannerImgHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.BANNER_IMG_HREF
     *
     * @param bannerImgHref the value for APP_BANNER.BANNER_IMG_HREF
     *
     * @mbggenerated
     */
    public void setBannerImgHref(String bannerImgHref) {
        this.bannerImgHref = bannerImgHref == null ? null : bannerImgHref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.BANNER_PRIORITY
     *
     * @return the value of APP_BANNER.BANNER_PRIORITY
     *
     * @mbggenerated
     */
    public String getBannerPriority() {
        return bannerPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.BANNER_PRIORITY
     *
     * @param bannerPriority the value for APP_BANNER.BANNER_PRIORITY
     *
     * @mbggenerated
     */
    public void setBannerPriority(String bannerPriority) {
        this.bannerPriority = bannerPriority == null ? null : bannerPriority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.BANNER_DESC
     *
     * @return the value of APP_BANNER.BANNER_DESC
     *
     * @mbggenerated
     */
    public String getBannerDesc() {
        return bannerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.BANNER_DESC
     *
     * @param bannerDesc the value for APP_BANNER.BANNER_DESC
     *
     * @mbggenerated
     */
    public void setBannerDesc(String bannerDesc) {
        this.bannerDesc = bannerDesc == null ? null : bannerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.CREATE_DATE
     *
     * @return the value of APP_BANNER.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.CREATE_DATE
     *
     * @param createDate the value for APP_BANNER.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.UPDATE_DATE
     *
     * @return the value of APP_BANNER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.UPDATE_DATE
     *
     * @param updateDate the value for APP_BANNER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.LAST_UPDATE_USER
     *
     * @return the value of APP_BANNER.LAST_UPDATE_USER
     *
     * @mbggenerated
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.LAST_UPDATE_USER
     *
     * @param lastUpdateUser the value for APP_BANNER.LAST_UPDATE_USER
     *
     * @mbggenerated
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BANNER.APP_TERM_TYPE
     *
     * @return the value of APP_BANNER.APP_TERM_TYPE
     *
     * @mbggenerated
     */
    public String getAppTermType() {
        return appTermType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BANNER.APP_TERM_TYPE
     *
     * @param appTermType the value for APP_BANNER.APP_TERM_TYPE
     *
     * @mbggenerated
     */
    public void setAppTermType(String appTermType) {
        this.appTermType = appTermType == null ? null : appTermType.trim();
    }
}